apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
  labels:
    app: guestbook
    tier: frontend
  annotations: 
    service.beta.kubernetes.io/azure-dns-label-name: guestbook-arc-demo
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: guestbook
    tier: frontend
