apiVersion: v1
kind: Service

metadata:
  name: redis-leader
  namespace: default
  labels:
    app: redis
    role: leader
    tier: backend
  annotations: 
    service.beta.kubernetes.io/azure-dns-label-name: redis-arc-demo
spec:
  type: LoadBalancer
  ports:
  - port: 6379
    targetPort: 6379

  selector:
    app: redis
    role: leader
    tier: backend