apiVersion: v1
kind: Service
metadata:
  name: redis-follower
  namespace: default
  labels:
    app: redis
    role: follower
    tier: backend
  annotations: 
    service.beta.kubernetes.io/azure-dns-label-name: redis-follower-arc-demo
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 6379
  selector:
    app: redis
    role: follower
    tier: backend